exercise4/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#top"
  get 'home/about', to: 'home#about'

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  resources :users, only: [:show, :edit, :update, :index]do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

exercise4/app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
    validates :body,    length: { maximum: 200 }

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end 
end

exercise4/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
#リレーション
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower


  has_one_attached :profile_image
  
  validates :name, uniqueness: true
  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  
def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
end

exercise4/app/controllers/relationship_controller.rb
class RelationshipController < ApplicationController
  # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end


end

exercise4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header class="shadow-sm">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
  <a class="navbar-brand p-1" href="/">Bookers</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
  <ul class="navbar-nav ml-auto">

    <% if user_signed_in? %>
        <!--ログイン中のヘッダー-->
      <li class="nav-link navbar-text">
        <%= link_to user_path(current_user.id) do%>
        <i class= "fas fa-home"></i>Home
      <%end%>
      </li>
      
      <li class="nav-link navbar-text">
        <%= link_to users_path do %>
        <i class="fas fa-users"></i>Users
        <%end%>
      </li>
      <li class="nav-link navbar-text">
        <%= link_to books_path do %>
        <i class="fas fa-book-open"></i>Books
        <%end%>
      </li>
      <li class="nav-link navbar-text">
        <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fas fa-sign-out-alt"></i>Log out
        <%end%>
      </li>

    <% else %>
        <!--ログアウト中のヘッダー-->
      <li class="nav-link navbar-text">
        <%= link_to root_path do%>
        <i class= "fas fa-home"></i>Home
      <%end%>
      </li>
      <li class="nav-link navbar-text">
        <%= link_to home_about_path do %>
        <i class="fas fa-link"></i>About
        <%end%>
      </li>
      <li class="nav-link navbar-text">
        <%= link_to new_user_registration_path do %>
        <i class="fas fa-user-plus"></i>Sign up
        <%end%>
      </li>
      <li class="nav-link navbar-text">
        <%= link_to new_user_session_path do %>
        <i class="fas fa-sign-in-alt"></i>Log in
        <%end%>
      </li>

    <% end %>
  </ul>
  </div>
  </div>
  </nav>
</header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
    <footer>
  <div class='container mt-5'>
  <div class='row'>
    <div class='mx-auto'>
    <p>CopyRight Infratop.inc</p>
    </div>
  </div>
  </div>
</footer>
</html>